export const hotels = [
  {
    name: "Castelo Valenzino",
    city: "Umbertide",
    country: "Włochy",
    rating: 8.6,
    description: "Fantastyczny",
    ratings: "183 opinii",
    img: "./img/castello.webp",
  },
  {
    name: "Hotel Palace",
    city: "Battipaglia",
    country: "Włochy",
    rating: 8.6,
    description: "Fantastyczny",
    ratings: "1 495 opinii",
    img: "./img/palace.webp",
  },
  {
    name: "Santa Marina Guesthouse",
    city: "Aridea",
    country: "Grecja",
    rating: 8.2,
    description: "Bardzo dobry",
    ratings: "848 opinii",
    img: "./img/marina.webp",
  },
  {
    name: "Hotel Paradiso",
    city: "Castel Volturno",
    country: "Włochy",
    rating: 8.5,
    description: "Bardzo dobry",
    ratings: "60 opinii",
    img: "./img/paradiso.webp",
  },
];
